/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ArticoliRouteImport } from './routes/articoli'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriaCatRouteImport } from './routes/categoria.$cat'
import { Route as ArticoliSlugRouteImport } from './routes/articoli.$slug'

const ArticoliRoute = ArticoliRouteImport.update({
  id: '/articoli',
  path: '/articoli',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaCatRoute = CategoriaCatRouteImport.update({
  id: '/categoria/$cat',
  path: '/categoria/$cat',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticoliSlugRoute = ArticoliSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticoliRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articoli': typeof ArticoliRouteWithChildren
  '/articoli/$slug': typeof ArticoliSlugRoute
  '/categoria/$cat': typeof CategoriaCatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articoli': typeof ArticoliRouteWithChildren
  '/articoli/$slug': typeof ArticoliSlugRoute
  '/categoria/$cat': typeof CategoriaCatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articoli': typeof ArticoliRouteWithChildren
  '/articoli/$slug': typeof ArticoliSlugRoute
  '/categoria/$cat': typeof CategoriaCatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/articoli'
    | '/articoli/$slug'
    | '/categoria/$cat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/articoli' | '/articoli/$slug' | '/categoria/$cat'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/articoli'
    | '/articoli/$slug'
    | '/categoria/$cat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArticoliRoute: typeof ArticoliRouteWithChildren
  CategoriaCatRoute: typeof CategoriaCatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/articoli': {
      id: '/articoli'
      path: '/articoli'
      fullPath: '/articoli'
      preLoaderRoute: typeof ArticoliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$cat': {
      id: '/categoria/$cat'
      path: '/categoria/$cat'
      fullPath: '/categoria/$cat'
      preLoaderRoute: typeof CategoriaCatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articoli/$slug': {
      id: '/articoli/$slug'
      path: '/$slug'
      fullPath: '/articoli/$slug'
      preLoaderRoute: typeof ArticoliSlugRouteImport
      parentRoute: typeof ArticoliRoute
    }
  }
}

interface ArticoliRouteChildren {
  ArticoliSlugRoute: typeof ArticoliSlugRoute
}

const ArticoliRouteChildren: ArticoliRouteChildren = {
  ArticoliSlugRoute: ArticoliSlugRoute,
}

const ArticoliRouteWithChildren = ArticoliRoute._addFileChildren(
  ArticoliRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArticoliRoute: ArticoliRouteWithChildren,
  CategoriaCatRoute: CategoriaCatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
